PROGRAMS=uspsv1 uspsv2 uspsv3 uspsv3

all: $(PROGRAMS)

uspsv1: uspsv1.o
	gcc -o $@ $^

uspsv2: uspsv2.o
	gcc: -o $@ $^

uspsv3: uspsv3.o
	gcc: -o $@ $^

uspsv4: uspsv4.o
	gcc: -o $@ $^

uspsv1.o: uspsv1.c
uspsv2.o: uspsv2.c
uspsv3.o: uspsv3.c
uspsv4.o: uspsv4.c

clean:
	rm - f $(PROGRAMS) *.O

